// FAVORITE
export const ADD_TO_FAVORITE = 'cart/ADD_TO_FAVORITE';
export const REMOVE_TO_FAVORITE = 'cart/REMOVE_TO_FAVORITE';

// CART
export const ADD_TO_CART = 'cart/ADD_TO_CART';
export const FAKE_ADD_TO_CART = 'cart/FAKE_ADD_TO_CART';
export const SELECTED_ADD_TO_CART = 'cart/SELECTED_ADD_TO_CART';

export const CHANGE_QUANTITY = 'cart/CHANGE_QUANTITY';
export const REMOVE_ITEM_CART = 'cart/REMOVE_ITEM_CART';
export const REMOVE_ITEM_FAKE_CART = 'cart/REMOVE_ITEM_FAKE_CART';

export const SELECTED_REMOVE_ITEM_CART = 'cart/SELECTED_REMOVE_ITEM_CART';
export const CLEAR_CART = 'cart/CLEAR_CART';
export const LOADING_CART = 'cart/LOADING_CART';
export const CLEAR_FAKE_CART = 'cart/CLEAR_FAKE_CART';
export const CLEAR_SELECTED_CART = 'cart/CLEAR_SELECTED_CART';

export const CHANGE_SHIPPING_OPTION = 'cart/CHANGE_SHIPPING_OPTION';
export const CHANGE_PAYMENT_METHOD = 'cart/CHANGE_PAYMENT_METHOD';
export const CHANGE_STORE_OPTION = 'cart/CHANGE_STORE_OPTION';
export const CHANGE_PROMOTION_STORE_OPTION = 'cart/CHANGE_PROMOTION_STORE_OPTION';
export const CHANGE_SHIPPING_TYPE = 'cart/CHANGE_SHIPPING_TYPE';
export const CHANGE_COUPON = 'cart/CHANGE_COUPON';
export const CLEAR_COUPON = 'cart/CLEAR_COUPON';

export const UPDATE_NEW_ITEM_ADD = 'cart/UPDATE_NEW_ITEM_ADD';
export const FAKE_UPDATE_NEW_ITEM_ADD = 'cart/FAKE_UPDATE_NEW_ITEM_ADD';
export const SELECTED_UPDATE_NEW_ITEM_ADD = 'cart/SELECTED_UPDATE_NEW_ITEM_ADD';

export const GET_ADDRESSES = 'cart/GET_ADDRESSES';
export const GET_ADDRESSES_SUCCESS = 'cart/GET_ADDRESSES_SUCCESS';

export const GET_SHIPPING_OPTIONS = 'cart/GET_SHIPPING_OPTIONS';
export const POST_ORDER_PAYMENT = 'cart/POST_ORDER_PAYMENT';
export const POST_UPDATE_DEFAULT_ADDRESS = 'cart/POST_UPDATE_DEFAULT_ADDRESS';

export const CHECK_PRODUCTS_HAVE_PROMOTION = 'cart/CHECK_PRODUCTS_HAVE_PROMOTION';
export const LOAD_PROMOTION_OF_STORE_WITH_PRODUCT = 'cart/LOAD_PROMOTION_OF_STORE_WITH_PRODUCT';
export const LOAD_DELIVER_PARTNER = 'cart/LOAD_DELIVER_PARTNER';

// new cart Gt-link

export const SET_AMOUNT_CART = 'cart/SET_AMOUNT_CART';

export const LOAD_STORE_INFO = 'cart/LOAD_STORE_INFO';
export const CREATE_ODER = 'cart/CREATE_ODER';
export const CHECK_ORDER_COUPON = 'cart/CHECK_ORDER_COUPON';

export const PAYMENT_WITH_E_WALLET = 'cart/PAYMENT_WITH_E_WALLET';
export const CHANGE_MY_ORDER_SUCCESS = 'cart/CHANGE_MY_ORDER_SUCCESS';

export const WISHLIST_LIST = 'cart/WISHLIST_LIST';
export const WISHLIST_ADD = 'cart/WISHLIST_ADD';
export const WISHLIST_REMOVE = 'cart/WISHLIST_REMOVE';

